[package]
name = "dnsmole"
version = "0.1.0"
authors = ["Guillaume Brogi <gui-gui@netcourrier.com>"]
description = "a DNS tunnel server and client"

[dependencies]
clap = {version = "2", features = ["yaml"]}
